# Generated by Django 4.2.7 on 2026-04-24 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Maqola nomi')),
                ('pdf_file', models.FileField(help_text='Faqat PDF format qabul qilinadi', upload_to='articles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF fayl')),
                ('additional_files', models.FileField(blank=True, help_text='ZIP yoki RAR formatida', null=True, upload_to='articles/additional/%Y/%m/', verbose_name="Qo'shimcha fayllar (rasm, jadval va h.k.)")),
                ('abstract', models.TextField(blank=True, verbose_name='Annotatsiya')),
                ('keywords', models.CharField(blank=True, help_text='Vergul bilan ajrating', max_length=500, verbose_name="Kalit so'zlar")),
                ('author_name', models.CharField(max_length=200, verbose_name='Muallif FIO')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('author_phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('author_degree', models.CharField(blank=True, max_length=100, verbose_name='Ilmiy daraja')),
                ('author_workplace', models.CharField(blank=True, max_length=300, verbose_name='Ish joyi')),
                ('author_orcid', models.CharField(blank=True, max_length=100, verbose_name='ORCID ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Bekor qilingan'), ('published', 'Nashr etilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('payment_status', models.CharField(choices=[('pending', "To'lanmagan"), ('paid', "To'langan"), ('refunded', 'Qaytarilgan')], default='pending', max_length=20, verbose_name="To'lov holati")),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="To'lov miqdori")),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name="To'lov sanasi")),
                ('payment_transaction_id', models.CharField(blank=True, max_length=200, verbose_name='Tranzaksiya ID')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Bekor qilish sababi')),
                ('rejection_date', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilish sanasi')),
                ('rejection_notified', models.BooleanField(default=False, verbose_name='Email yuborildi')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr qilingan vaqt')),
                ('notes', models.TextField(blank=True, verbose_name='Izohlar (admin uchun)')),
                ('views_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Yuklab olishlar soni')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
