# Generated by Django 5.2.13 on 2026-04-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('chemistry', 'Kimyo fanlari (noorganik, organik, analitik, fizikaviy kimyo)'), ('technology', 'Texnologiya fanlari (oziq-ovqat, kimyoviy, neft va gaz texnologiyasi)'), ('materials', 'Materialshunoslik va nanotexnologiyalar'), ('ecology', 'Atrof-muhit muhofazasi va ekologiya'), ('biotechnology', 'Biotexnologiya va biokimyo')], default='chemistry', max_length=50, verbose_name="Yo'nalish"),
        ),
    ]
