# Generated by Django 5.2.13 on 2026-04-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='payment_link_sent',
            field=models.BooleanField(default=False, verbose_name="To'lov linki yuborildi"),
        ),
        migrations.AddField(
            model_name='article',
            name='payment_link_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'lov linki yuborilgan vaqt"),
        ),
        migrations.AddField(
            model_name='article',
            name='payment_link_sent_count',
            field=models.IntegerField(default=0, verbose_name="To'lov linki yuborilgan soni"),
        ),
    ]
