# Generated by Django 5.2.13 on 2026-04-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_article_payment_link_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('position', models.CharField(choices=[('editor_in_chief', 'Bosh muharrir'), ('deputy_editor', "Bosh muharrir o'rinbosari"), ('executive_editor', "Mas'ul muharrir"), ('section_editor', "Bo'lim muharriri"), ('member', "Tahririyat hay'ati a'zosi"), ('technical_editor', 'Texnik muharrir')], max_length=50, verbose_name='Lavozim')),
                ('academic_degree', models.CharField(blank=True, max_length=200, verbose_name='Ilmiy daraja')),
                ('workplace', models.CharField(max_length=300, verbose_name='Ish joyi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('orcid', models.CharField(blank=True, max_length=100, verbose_name='ORCID ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='editorial/%Y/', verbose_name='Rasm')),
                ('order', models.IntegerField(default=0, help_text="Kichik raqam birinchi ko'rsatiladi", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('bio', models.TextField(blank=True, verbose_name='Biografiya')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
            options={
                'verbose_name': "Tahririyat a'zosi",
                'verbose_name_plural': "Tahririyat hay'ati",
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
