# Generated by Django 5.2.13 on 2026-04-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_editorialmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Hujjat nomi yoki tavsifi', max_length=300, verbose_name='Sarlavha')),
                ('image', models.ImageField(upload_to='regulatory_docs/%Y/%m/', verbose_name='Hujjat rasmi')),
                ('order', models.IntegerField(default=0, help_text="Kichik raqam birinchi ko'rsatiladi", verbose_name='Tartib raqami')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
            ],
            options={
                'verbose_name': 'Meyoriy hujjat',
                'verbose_name_plural': 'Meyoriy hujjatlar',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
