# Generated by Django 5.2.13 on 2026-04-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_regulatorydocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatorydocument',
            name='title',
        ),
    ]
