# Generated by Django 5.2.13 on 2026-04-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_regulatorydocument_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulatorydocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Meyoriy hujjat', 'verbose_name_plural': 'Meyoriy hujjatlar'},
        ),
        migrations.RemoveField(
            model_name='regulatorydocument',
            name='order',
        ),
    ]
