# Generated by Django 5.2.13 on 2026-04-26 18:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_regulatorydocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(help_text='URL uchun noyob nom', max_length=300, unique=True, verbose_name='Slug')),
                ('category', models.CharField(help_text='Masalan: Muhim, Umumiy, Eslatma', max_length=100, verbose_name='Kategoriya')),
                ('excerpt', models.TextField(help_text='Qisqa tavsif', max_length=500, verbose_name='Qisqacha')),
                ('content', models.TextField(verbose_name="To'liq matn")),
                ('priority', models.CharField(choices=[('yuqori', 'Yuqori'), ('orta', "O'rta"), ('past', 'Past')], default='orta', max_length=10, verbose_name='Muhimlik darajasi')),
                ('icon', models.CharField(choices=[('warning', 'Ogohlantirish'), ('info', "Ma'lumot"), ('document', 'Hujjat')], default='info', max_length=10, verbose_name='Ikonka')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nashr sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('slug', models.SlugField(help_text='URL uchun noyob nom (masalan: yangi-laboratoriya-ochildi)', max_length=300, unique=True, verbose_name='Slug')),
                ('category', models.CharField(help_text='Masalan: Tadbirlar, Yangiliklar, Ilmiy', max_length=100, verbose_name='Kategoriya')),
                ('image', models.ImageField(upload_to='news/%Y/%m/', verbose_name='Rasm')),
                ('excerpt', models.TextField(help_text="Qisqa tavsif (ro'yxatda ko'rsatiladi)", max_length=500, verbose_name='Qisqacha')),
                ('content', models.TextField(verbose_name="To'liq matn")),
                ('author', models.CharField(default='Admin', max_length=200, verbose_name='Muallif')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nashr sanasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_date'],
            },
        ),
    ]
