# Generated by Django 5.2.13 on 2026-04-26 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_announcement_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='details',
            field=models.TextField(blank=True, help_text="Qo'shimcha tafsilotlar, shartlar, talablar va h.k.", verbose_name="Batafsil ma'lumot"),
        ),
        migrations.AddField(
            model_name='announcement',
            name='validity_end',
            field=models.DateField(blank=True, help_text="E'lon qachongacha amal qiladi", null=True, verbose_name='Amal qilish tugashi'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='validity_start',
            field=models.DateField(blank=True, help_text="E'lon qachondan amal qila boshlaydi", null=True, verbose_name='Amal qilish boshlanishi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('muhim', "Muhim e'lon"), ('umumiy', "Umumiy ma'lumot"), ('eslatma', 'Eslatma'), ('imtihon', "Imtihon e'loni"), ('konferensiya', 'Konferensiya'), ('konkurs', 'Konkurs'), ('muddat', "Muddat e'loni"), ('boshqa', 'Boshqa')], default='umumiy', max_length=50, verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="E'lon qo'shilgan sana"),
        ),
    ]
