# Generated by Django 5.2.13 on 2026-04-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_announcement_details_announcement_validity_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialmember',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='email',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='orcid',
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='phone',
        ),
    ]
