# Generated by Django 5.2.13 on 2026-04-26 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_remove_editorialmember_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorialmember',
            options={'ordering': ['full_name'], 'verbose_name': "Tahririyat a'zosi", 'verbose_name_plural': "Tahririyat hay'ati"},
        ),
        migrations.RemoveField(
            model_name='editorialmember',
            name='order',
        ),
    ]
