# Generated by Django 5.2.13 on 2026-04-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_editorialmember_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='details',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='priority',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="E'lon qo'shilgan sana"),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Nashr sanasi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name="Ko'rishlar soni"),
        ),
    ]
