# Generated by Django 5.0.4 on 2026-04-29 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_remove_announcement_details_remove_announcement_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('workplace', models.CharField(blank=True, max_length=300, verbose_name='Ish joyi')),
                ('academic_degree', models.CharField(blank=True, max_length=100, verbose_name='Ilmiy daraja')),
                ('total_articles', models.IntegerField(default=0, editable=False, verbose_name='Jami maqolalar')),
                ('approved_articles', models.IntegerField(default=0, editable=False, verbose_name='Tasdiqlangan')),
                ('rejected_articles', models.IntegerField(default=0, editable=False, verbose_name='Rad etilgan')),
                ('pending_articles', models.IntegerField(default=0, editable=False, verbose_name='Kutilmoqda')),
                ('first_submission', models.DateTimeField(auto_now_add=True, verbose_name='Birinchi yuborgan vaqti')),
                ('last_submission', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yuborgan vaqti')),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
                'ordering': ['-last_submission'],
                'unique_together': {('full_name', 'email', 'phone')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='pages.author', verbose_name='Muallif'),
        ),
    ]
