# Generated by Django 5.2.13 on 2026-04-29 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_author_article_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Lavozimi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviewers/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Taqrizchi',
                'verbose_name_plural': 'Taqrizchilar',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holat')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rad etish sababi')),
                ('rejection_file', models.FileField(blank=True, null=True, upload_to='reviews/%Y/%m/', verbose_name='Fayl')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Biriktirilgan vaqt')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name="Ko'rib chiqilgan vaqt")),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.article')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.reviewer')),
            ],
            options={
                'verbose_name': 'Taqriz',
                'verbose_name_plural': 'Taqrizlar',
                'ordering': ['-assigned_at'],
                'unique_together': {('article', 'reviewer')},
            },
        ),
    ]
