# Generated by Django 5.2.13 on 2026-04-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_reviewer_articlereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewer',
            name='specialization',
            field=models.CharField(choices=[('chemistry', 'Kimyo fanlari'), ('technology', 'Texnologiya fanlari'), ('materials', 'Materialshunoslik va nanotexnologiyalar'), ('ecology', 'Atrof-muhit muhofazasi va ekologiya'), ('biotechnology', 'Biotexnologiya va biokimyo')], default='chemistry', max_length=50, verbose_name="Yo'nalish"),
        ),
    ]
