# Generated by Django 5.2.13 on 2026-04-30 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_reviewer_specialization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Masalan: 2026-yil, 5-tom, 2-son', max_length=300, verbose_name='Tom nomi')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('year', models.IntegerField(default=2026, verbose_name='Yil')),
                ('volume_number', models.IntegerField(default=1, verbose_name='Tom raqami')),
                ('issue_number', models.IntegerField(default=1, verbose_name='Son raqami')),
                ('max_articles', models.IntegerField(default=10, help_text='Tomga necha maqola kirishi mumkin', verbose_name='Maqolalar soni (belgilangan)')),
                ('status', models.CharField(choices=[('draft', 'Tayyorlanmoqda'), ('active', 'Faol (maqola qabul qilmoqda)'), ('published', 'Nashr etilgan')], default='draft', max_length=20, verbose_name='Holat')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='volumes/covers/', verbose_name='Muqova rasmi')),
                ('pdf_file', models.FileField(blank=True, help_text='Admin tomonidan tahrirlangan va chop etilgan tom PDF', null=True, upload_to='volumes/pdf/', verbose_name="To'liq tom PDF")),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Tom',
                'verbose_name_plural': 'Tomlar',
                'ordering': ['-year', '-volume_number', '-issue_number'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volume_articles', to='pages.volume', verbose_name='Tom'),
        ),
    ]
