# Generated by Django 5.2.13 on 2026-04-30 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_volume_article_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='subject',
            field=models.CharField(blank=True, choices=[('chemistry', 'Kimyo fanlari'), ('technology', 'Texnologiya fanlari'), ('materials', 'Materialshunoslik va nanotexnologiyalar'), ('ecology', 'Atrof-muhit muhofazasi va ekologiya'), ('biotechnology', 'Biotexnologiya va biokimyo'), ('mixed', "Aralash yo'nalishlar")], default='mixed', max_length=50, verbose_name="Fan yo'nalishi"),
        ),
        migrations.AddField(
            model_name='volume',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.CreateModel(
            name='VolumeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('chemistry', 'Kimyo fanlari'), ('technology', 'Texnologiya fanlari'), ('materials', 'Materialshunoslik va nanotexnologiyalar'), ('ecology', 'Atrof-muhit muhofazasi va ekologiya'), ('biotechnology', 'Biotexnologiya va biokimyo')], default='chemistry', max_length=50, verbose_name="Fan yo'nalishi")),
                ('title', models.CharField(max_length=500, verbose_name='Maqola mavzusi')),
                ('authors', models.CharField(help_text='Masalan: Karimov A., Rahimov B.', max_length=500, verbose_name='Avtorlari')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Nashr sanasi')),
                ('abstract', models.TextField(blank=True, verbose_name='Annotatsiya (ixtiyoriy)')),
                ('doi', models.CharField(blank=True, max_length=200, verbose_name='DOI')),
                ('pages', models.CharField(blank=True, help_text='Masalan: 12-18', max_length=50, verbose_name='Sahifalar')),
                ('views_count', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqt")),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_articles', to='pages.volume', verbose_name='Tom')),
            ],
            options={
                'verbose_name': 'Tom maqolasi',
                'verbose_name_plural': 'Tom maqolalari',
                'ordering': ['published_date', 'title'],
            },
        ),
    ]
