# Generated by Django 5.2.13 on 2026-04-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_volume_subject_volume_views_count_volumearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumearticle',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Alohida maqola PDF fayli', null=True, upload_to='volume_articles/pdf/', verbose_name='Maqola PDFi'),
        ),
    ]
