# Generated by Django 5.2.13 on 2026-05-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_volumearticle_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('source', models.CharField(choices=[('newsletter', 'Obuna formasi'), ('article', 'Maqola yuborish')], default='newsletter', max_length=20, verbose_name='Manba')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Obuna bo'lgan vaqt")),
            ],
            options={
                'verbose_name': 'Obunachi',
                'verbose_name_plural': 'Obunachlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
