# Generated by Django 5.2.15 on 2026-06-20 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.CharField(blank=True, default='Tahririyat', max_length=200, verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='volumearticle',
            name='keywords',
            field=models.CharField(blank=True, help_text='Vergul bilan ajrating', max_length=500, verbose_name="Kalit so'zlar"),
        ),
        migrations.AddField(
            model_name='volumearticle',
            name='references',
            field=models.TextField(blank=True, help_text='Har bir manba yangi qatordan', verbose_name="Adabiyotlar ro'yxati"),
        ),
        migrations.AddField(
            model_name='volumearticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(help_text='PDF, DOC yoki DOCX format qabul qilinadi', upload_to='articles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Maqola fayli'),
        ),
        migrations.AlterUniqueTogether(
            name='volumearticle',
            unique_together={('volume', 'slug')},
        ),
    ]
