# Generated by Django 5.2.13 on 2026-06-20 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_announcement_author_article_author_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sertifikat raqami'),
        ),
        migrations.AddField(
            model_name='article',
            name='certificate_pdf',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='generated/certificates/%Y/%m/', verbose_name='Sertifikat PDF'),
        ),
        migrations.AddField(
            model_name='article',
            name='co_authors',
            field=models.CharField(blank=True, help_text='Vergul bilan ajrating (masalan: Karimov A., Rahimov B.)', max_length=500, verbose_name='Ham mualliflar'),
        ),
        migrations.AddField(
            model_name='article',
            name='personal_pdf',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='generated/personal/%Y/%m/', verbose_name='Shaxsiy nashr PDF'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(help_text='Faqat PDF format qabul qilinadi', upload_to='articles/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Maqola fayli'),
        ),
    ]
