# Generated by Django 5.1.15 on 2026-06-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_article_pdf_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, help_text='Masalan: 10.1234/example', max_length=200, verbose_name='DOI'),
        ),
    ]
